FROM latkinsa/ol7-rvm:rvm-base

RUN rvm install --autolibs=1 2.4.3 --disable-dtrace

# COPY Gemfile Gemfile.lock /root/

# RUN bundle config --global path /bundle && \
#  bundle config --global bin /usr/local/bin && \
#  bundle install --local
